# Generated by Django 5.0.4 on 2024-10-29 08:54

import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Project',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('uuid', models.UUIDField(default=uuid.uuid4, editable=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('url', models.URLField()),
                ('name', models.CharField(max_length=255)),
                ('type', models.CharField(choices=[('SaaS', 'SaaS'), ('Hospitality', 'Hospitality'), ('Job Board', 'Job Board'), ('Legal Services', 'Legal Services'), ('Marketing', 'Marketing'), ('News and Magazine', 'News and Magazine'), ('Online Tools, Utilities', 'Online Tools, Utilities'), ('Ecommerce', 'Ecommerce'), ('Educational', 'Educational'), ('Entertainment', 'Entertainment'), ('Financial Services', 'Financial Services'), ('Health & Wellness', 'Health & Wellness'), ('Personal Blog', 'Personal Blog'), ('Real Estate', 'Real Estate'), ('Sports', 'Sports'), ('Travel and Tourism', 'Travel and Tourism')], default='SaaS', max_length=50)),
                ('summary', models.TextField()),
                ('blog_theme', models.TextField()),
                ('founders', models.TextField(blank=True)),
                ('key_features', models.TextField()),
                ('language', models.CharField(choices=[('English', 'English')], default='English', max_length=50)),
                ('target_audience_summary', models.TextField()),
                ('pain_points', models.TextField()),
                ('product_usage', models.TextField()),
                ('style', models.CharField(choices=[('Digital Art', 'Digital Art'), ('Photorealistic', 'Photorealistic'), ('Hyper-realistic', 'Hyper-realistic'), ('Oil Painting', 'Oil Painting'), ('Watercolor', 'Watercolor'), ('Cartoon', 'Cartoon'), ('Anime', 'Anime'), ('3D Render', '3D Render'), ('Sketch', 'Sketch'), ('Pop Art', 'Pop Art'), ('Minimalist', 'Minimalist'), ('Surrealist', 'Surrealist'), ('Impressionist', 'Impressionist'), ('Pixel Art', 'Pixel Art'), ('Concept Art', 'Concept Art'), ('Isometric', 'Isometric'), ('Low Poly', 'Low Poly'), ('Retro', 'Retro'), ('Cyberpunk', 'Cyberpunk'), ('Steampunk', 'Steampunk')], default='Digital Art', max_length=50)),
            ],
            options={
                'abstract': False,
            },
        ),
    ]
