# Generated by Django 5.1.3 on 2024-12-06 09:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0002_blogposttitlesuggestion_project_generatedblogpost_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='project',
            name='blog_theme',
            field=models.TextField(blank=True),
        ),
        migrations.AlterField(
            model_name='project',
            name='key_features',
            field=models.TextField(blank=True),
        ),
        migrations.AlterField(
            model_name='project',
            name='pain_points',
            field=models.TextField(blank=True),
        ),
        migrations.AlterField(
            model_name='project',
            name='product_usage',
            field=models.TextField(blank=True),
        ),
        migrations.AlterField(
            model_name='project',
            name='summary',
            field=models.TextField(blank=True),
        ),
        migrations.AlterField(
            model_name='project',
            name='target_audience_summary',
            field=models.TextField(blank=True),
        ),
    ]
