# Generated by Django 5.1.3 on 2024-12-06 10:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0003_alter_project_blog_theme_alter_project_key_features_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='project',
            name='links',
            field=models.TextField(blank=True),
        ),
        migrations.AlterField(
            model_name='project',
            name='language',
            field=models.CharField(choices=[('English', 'English'), ('Spanish', 'Spanish'), ('French', 'French'), ('German', 'German'), ('Italian', 'Italian'), ('Portuguese', 'Portuguese'), ('Russian', 'Russian'), ('Japanese', 'Japanese'), ('Cantonese', 'Cantonese'), ('Mandarin', 'Mandarin'), ('Arabic', 'Arabic'), ('Korean', 'Korean'), ('Hindi', 'Hindi'), ('Ukrainian', 'Ukrainian')], default='English', max_length=50),
        ),
    ]
