# Generated by Django 5.0.4 on 2024-10-31 06:14

import django.db.models.deletion
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0003_project_profile'),
    ]

    operations = [
        migrations.CreateModel(
            name='BlogPostTitleSuggestion',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('uuid', models.UUIDField(default=uuid.uuid4, editable=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('title', models.CharField(max_length=255)),
                ('description', models.TextField()),
                ('category', models.CharField(choices=[('General Audience', 'General Audience'), ('Niche Audience', 'Niche Audience'), ('Industry/Company', 'Industry/Company')], default='General Audience', max_length=50)),
                ('project', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='blog_post_title_suggestions', to='core.project')),
            ],
            options={
                'abstract': False,
            },
        ),
    ]
