# Generated by Django 5.1.3 on 2024-12-07 18:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0004_project_links_alter_project_language'),
    ]

    operations = [
        migrations.AddField(
            model_name='blogposttitlesuggestion',
            name='prompt',
            field=models.TextField(blank=True),
        ),
    ]
