# Generated by Django 5.0.4 on 2024-11-02 13:09

import django.db.models.deletion
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0004_blogposttitlesuggestion'),
    ]

    operations = [
        migrations.CreateModel(
            name='GeneratedBlogPost',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('uuid', models.UUIDField(default=uuid.uuid4, editable=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('title', models.CharField(max_length=250)),
                ('description', models.TextField(blank=True)),
                ('slug', models.SlugField(max_length=250)),
                ('tags', models.TextField()),
                ('content', models.TextField()),
                ('icon', models.ImageField(blank=True, upload_to='blog_post_icons/')),
                ('image', models.ImageField(blank=True, upload_to='blog_post_images/')),
                ('project', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='generated_blog_posts', to='core.project')),
            ],
            options={
                'abstract': False,
            },
        ),
    ]
