# Generated by Django 5.0.4 on 2024-11-02 13:14

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0005_generatedblogpost'),
    ]

    operations = [
        migrations.AlterField(
            model_name='generatedblogpost',
            name='title',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='generated_blog_posts', to='core.blogposttitlesuggestion'),
        ),
    ]
