# Generated by Django 5.1.5 on 2025-02-16 10:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0005_blogposttitlesuggestion_prompt'),
    ]

    operations = [
        migrations.AddField(
            model_name='blogposttitlesuggestion',
            name='content_type',
            field=models.CharField(choices=[('SHARING', 'Sharing'), ('SEO', 'SEO')], default='SHARING', max_length=20),
        ),
    ]
