# Generated by Django 5.1.3 on 2024-12-21 09:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0005_blogposttitlesuggestion_prompt'),
    ]

    operations = [
        migrations.AddField(
            model_name='profile',
            name='anthropic_api_key',
            field=models.CharField(blank=True, max_length=255),
        ),
        migrations.AddField(
            model_name='profile',
            name='replicate_api_key',
            field=models.CharField(blank=True, max_length=255),
        ),
    ]
