# Generated by Django 5.1.3 on 2025-02-21 11:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0006_blogposttitlesuggestion_content_type_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='project',
            name='date_analyzed',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='project',
            name='date_scraped',
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
