# Generated by Django 5.1.6 on 2025-02-22 07:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0006_blogposttitlesuggestion_content_type_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='blogposttitlesuggestion',
            name='user_score',
            field=models.SmallIntegerField(choices=[(-1, "Didn't Like"), (0, 'Undecided'), (1, 'Liked')], default=0, help_text="User's rating of the title suggestion"),
        ),
        migrations.AddField(
            model_name='project',
            name='date_analyzed',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='project',
            name='date_scraped',
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
