# Generated by Django 5.1.5 on 2025-02-16 11:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0006_blogposttitlesuggestion_content_type'),
    ]

    operations = [
        migrations.AddField(
            model_name='project',
            name='markdown_content',
            field=models.TextField(blank=True),
        ),
    ]
