# Generated by Django 5.1.6 on 2025-02-21 14:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0007_project_date_analyzed_project_date_scraped'),
    ]

    operations = [
        migrations.AddField(
            model_name='blogposttitlesuggestion',
            name='user_score',
            field=models.SmallIntegerField(choices=[(-1, "Didn't Like"), (0, 'Undecided'), (1, 'Liked')], default=0, help_text="User's rating of the title suggestion"),
        ),
    ]
