# Generated by Django 5.1.6 on 2025-02-28 09:52

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0007_blogposttitlesuggestion_user_score_and_more'),
        ('djstripe', '0014_2_9a'),
    ]

    operations = [
        migrations.AddField(
            model_name='profile',
            name='product',
            field=models.ForeignKey(blank=True, help_text="The user's Stripe Product object, if it exists", null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='profile', to='djstripe.product'),
        ),
        migrations.AddField(
            model_name='profile',
            name='state',
            field=models.CharField(choices=[('stranger', 'Stranger'), ('signed_up', 'Signed Up'), ('subscribed', 'Subscribed'), ('cancelled', 'Cancelled'), ('churned', 'Churned'), ('account_deleted', 'Account Deleted')], default='stranger', help_text="The current state of the user's profile", max_length=255),
        ),
        migrations.AlterField(
            model_name='project',
            name='type',
            field=models.CharField(choices=[('SaaS', 'SaaS'), ('Hospitality', 'Hospitality'), ('Job Board', 'Job Board'), ('Legal Services', 'Legal Services'), ('Marketing', 'Marketing'), ('News and Magazine', 'News and Magazine'), ('Online Tools, Utilities', 'Online Tools, Utilities'), ('Ecommerce', 'Ecommerce'), ('Educational', 'Educational'), ('Entertainment', 'Entertainment'), ('Financial Services', 'Financial Services'), ('Health & Wellness', 'Health & Wellness'), ('Personal Blog', 'Personal Blog'), ('Real Estate', 'Real Estate'), ('Sports', 'Sports'), ('Travel and Tourism', 'Travel and Tourism'), ('Other', 'Other')], default='SaaS', max_length=50),
        ),
    ]
