# Generated by Django 5.1.6 on 2025-03-08 07:54

import django.db.models.deletion
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0008_profile_product_profile_state_alter_project_type'),
    ]

    operations = [
        migrations.CreateModel(
            name='ProjectPage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('uuid', models.UUIDField(default=uuid.uuid4, editable=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('url', models.URLField(unique=True)),
                ('html_content', models.TextField(blank=True, default='')),
                ('date_scraped', models.DateTimeField(blank=True, null=True)),
                ('title', models.CharField(blank=True, default='', max_length=500)),
                ('description', models.TextField(blank=True, default='')),
                ('markdown_content', models.TextField(blank=True, default='')),
                ('date_analyzed', models.DateTimeField(blank=True, null=True)),
                ('type', models.CharField(choices=[('Blog', 'Blog'), ('About', 'About'), ('Contact', 'Contact'), ('FAQ', 'FAQ'), ('Terms of Service', 'Terms of Service'), ('Privacy Policy', 'Privacy Policy'), ('Pricing', 'Pricing'), ('Other', 'Other')], default='Blog', max_length=255)),
                ('type_ai_guess', models.CharField(max_length=255)),
                ('summary', models.TextField(blank=True)),
                ('project', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='project_pages', to='core.project')),
            ],
            options={
                'abstract': False,
            },
        ),
    ]
