# Generated by Django 5.1.5 on 2025-02-16 12:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0008_project_description_project_html_content_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='blogposttitlesuggestion',
            name='search_intent',
            field=models.CharField(blank=True, max_length=50),
        ),
        migrations.AddField(
            model_name='blogposttitlesuggestion',
            name='seo_score',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='blogposttitlesuggestion',
            name='suggested_meta_description',
            field=models.TextField(blank=True),
        ),
        migrations.AddField(
            model_name='blogposttitlesuggestion',
            name='target_keywords',
            field=models.JSONField(blank=True, default=list, null=True),
        ),
    ]
