# Generated by Django 5.1.5 on 2025-02-16 15:02

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0009_blogposttitlesuggestion_search_intent_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='blogposttitlesuggestion',
            name='search_intent',
        ),
        migrations.RemoveField(
            model_name='blogposttitlesuggestion',
            name='seo_score',
        ),
    ]
