# Generated by Django 5.1.6 on 2025-03-09 08:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0009_projectpage'),
    ]

    operations = [
        migrations.AlterField(
            model_name='projectpage',
            name='url',
            field=models.URLField(),
        ),
        migrations.AlterUniqueTogether(
            name='projectpage',
            unique_together={('project', 'url')},
        ),
    ]
