# Generated by Django 5.1.6 on 2025-02-21 15:12

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0009_blogposttitlesuggestion_archived'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='blogposttitlesuggestion',
            name='archived',
        ),
    ]
