# Generated by Django 5.1.6 on 2025-03-09 09:46

import django.db.models.deletion
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0010_alter_projectpage_url_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='PricingPageUpdatesSuggestion',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('uuid', models.UUIDField(default=uuid.uuid4, editable=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('user_prompt', models.TextField(blank=True)),
                ('current_pricing_strategy', models.TextField()),
                ('suggested_pricing_strategy', models.TextField()),
                ('project', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='pricing_page_updates', to='core.project')),
                ('project_page', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='pricing_page_updates', to='core.projectpage')),
            ],
            options={
                'abstract': False,
            },
        ),
    ]
