# Generated by Django 5.1.6 on 2025-03-11 08:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0012_alter_projectpage_type'),
    ]

    operations = [
        migrations.AddField(
            model_name='pricingpageupdatessuggestion',
            name='strategy_name',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AlterUniqueTogether(
            name='projectpage',
            unique_together={('project', 'url', 'type')},
        ),
    ]
