# Generated by Django 5.1.7 on 2025-03-19 06:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0014_alter_projectpage_type'),
    ]

    operations = [
        migrations.AddField(
            model_name='project',
            name='competitors',
            field=models.TextField(blank=True),
        ),
    ]
