# Generated by Django 5.1.7 on 2025-03-22 09:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0016_remove_project_competitors_competitor'),
    ]

    operations = [
        migrations.AddField(
            model_name='project',
            name='competitors_list',
            field=models.TextField(blank=True),
        ),
    ]
