# Generated by Django 5.1.7 on 2025-03-25 06:38

import django.db.models.deletion
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0017_project_competitors_list'),
    ]

    operations = [
        migrations.AddField(
            model_name='competitor',
            name='competitor_analysis',
            field=models.TextField(blank=True),
        ),
        migrations.AddField(
            model_name='competitor',
            name='date_analyzed',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='competitor',
            name='date_scraped',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='competitor',
            name='homepage_description',
            field=models.TextField(blank=True, default=''),
        ),
        migrations.AddField(
            model_name='competitor',
            name='homepage_title',
            field=models.CharField(blank=True, default='', max_length=500),
        ),
        migrations.AddField(
            model_name='competitor',
            name='key_benefits',
            field=models.TextField(blank=True),
        ),
        migrations.AddField(
            model_name='competitor',
            name='key_differences',
            field=models.TextField(blank=True),
        ),
        migrations.AddField(
            model_name='competitor',
            name='key_drawbacks',
            field=models.TextField(blank=True),
        ),
        migrations.AddField(
            model_name='competitor',
            name='key_features',
            field=models.TextField(blank=True),
        ),
        migrations.AddField(
            model_name='competitor',
            name='links',
            field=models.JSONField(blank=True, default=list, null=True),
        ),
        migrations.AddField(
            model_name='competitor',
            name='markdown_content',
            field=models.TextField(blank=True),
        ),
        migrations.AddField(
            model_name='competitor',
            name='opportunities',
            field=models.TextField(blank=True),
        ),
        migrations.AddField(
            model_name='competitor',
            name='strengths',
            field=models.TextField(blank=True),
        ),
        migrations.AddField(
            model_name='competitor',
            name='summary',
            field=models.TextField(blank=True),
        ),
        migrations.AddField(
            model_name='competitor',
            name='threats',
            field=models.TextField(blank=True),
        ),
        migrations.AddField(
            model_name='competitor',
            name='weaknesses',
            field=models.TextField(blank=True),
        ),
        migrations.CreateModel(
            name='CompetitorComparisonBlogPost',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('uuid', models.UUIDField(default=uuid.uuid4, editable=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('title', models.CharField(max_length=255)),
                ('description', models.TextField()),
                ('slug', models.SlugField(max_length=250)),
                ('content', models.TextField()),
                ('competitor', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='competitor_comparison_blog_posts', to='core.competitor')),
                ('project', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='competitor_comparison_blog_posts', to='core.project')),
            ],
            options={
                'abstract': False,
            },
        ),
    ]
