# Generated by Django 5.1.7 on 2025-05-09 08:25

import django.db.models.deletion
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0019_feedback'),
    ]

    operations = [
        migrations.AddField(
            model_name='project',
            name='proposed_keywords',
            field=models.TextField(blank=True),
        ),
        migrations.CreateModel(
            name='Keyword',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('uuid', models.UUIDField(default=uuid.uuid4, editable=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('keyword_text', models.CharField(help_text='The keyword string', max_length=255)),
                ('volume', models.IntegerField(blank=True, help_text='The search volume of the keyword', null=True)),
                ('cpc_currency', models.CharField(blank=True, help_text='The currency of the CPC value', max_length=10)),
                ('cpc_value', models.DecimalField(blank=True, decimal_places=2, help_text='The cost per click value', max_digits=10, null=True)),
                ('competition', models.FloatField(blank=True, help_text='The competition metric of the keyword (0 to 1)', null=True)),
                ('country', models.CharField(blank=True, help_text='The country for which metrics were fetched', max_length=10)),
                ('data_source', models.CharField(blank=True, choices=[('gkp', 'Google Keyword Planner'), ('cli', 'Clickstream')], default='gkp', help_text='The data source for the keyword metrics', max_length=3)),
                ('last_fetched_at', models.DateTimeField(auto_now=True, help_text='Timestamp of when the data was last fetched')),
            ],
            options={
                'verbose_name': 'Keyword',
                'verbose_name_plural': 'Keywords',
                'unique_together': {('keyword_text', 'country', 'data_source')},
            },
        ),
        migrations.CreateModel(
            name='KeywordTrend',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('uuid', models.UUIDField(default=uuid.uuid4, editable=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('month', models.CharField(help_text='The month of this volume (e.g., May)', max_length=10)),
                ('year', models.IntegerField(help_text='The year of this volume (e.g., 2019)')),
                ('value', models.IntegerField(help_text='The search volume of the keyword for the given month')),
                ('keyword', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='trends', to='core.keyword')),
            ],
            options={
                'verbose_name': 'Keyword Trend',
                'verbose_name_plural': 'Keyword Trends',
                'ordering': ['keyword', 'year', 'month'],
                'unique_together': {('keyword', 'month', 'year')},
            },
        ),
        migrations.CreateModel(
            name='ProjectKeyword',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('uuid', models.UUIDField(default=uuid.uuid4, editable=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('date_associated', models.DateTimeField(auto_now_add=True, help_text='When the keyword was associated with the project')),
                ('keyword', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='keyword_projects', to='core.keyword')),
                ('project', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='project_keywords', to='core.project')),
            ],
            options={
                'verbose_name': 'Project Keyword',
                'verbose_name_plural': 'Project Keywords',
                'unique_together': {('project', 'keyword')},
            },
        ),
    ]
