# Generated by Django 5.2.1 on 2025-05-10 06:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0020_project_proposed_keywords_keyword_keywordtrend_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='projectkeyword',
            name='use',
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name='keyword',
            name='country',
            field=models.CharField(blank=True, default='us', help_text='The country for which metrics were fetched', max_length=10),
        ),
    ]
