# Generated by Django 5.2.1 on 2025-05-12 08:15

import django.db.models.deletion
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0023_alter_blogpost_status'),
    ]

    operations = [
        migrations.AddField(
            model_name='blogposttitlesuggestion',
            name='archived',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='generatedblogpost',
            name='posted',
            field=models.BooleanField(default=False),
        ),
        migrations.CreateModel(
            name='AutoSubmittionSetting',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('uuid', models.UUIDField(default=uuid.uuid4, editable=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('endpoint_url', models.URLField(help_text='The endpoint to which posts will be automatically submitted.', max_length=500)),
                ('body', models.JSONField(blank=True, default=dict, help_text='Key-value pairs for the request body.', null=True)),
                ('header', models.JSONField(blank=True, default=dict, help_text='Key-value pairs for the request headers.', null=True)),
                ('posts_per_month', models.PositiveIntegerField(default=1, help_text='How many posts to publish per month.')),
                ('preferred_timezone', models.CharField(blank=True, help_text='Preferred timezone for publishing posts.', max_length=64, null=True)),
                ('preferred_time', models.TimeField(blank=True, help_text='Preferred time of day to publish posts.', null=True)),
                ('project', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='auto_submittion_settings', to='core.project')),
            ],
            options={
                'abstract': False,
            },
        ),
    ]
