# Generated by Django 5.2.1 on 2025-05-12 06:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0024_blogposttitlesuggestion_archived_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='autosubmittionsettings',
            name='posts_per_day',
        ),
        migrations.AddField(
            model_name='autosubmittionsettings',
            name='posts_per_month',
            field=models.PositiveIntegerField(default=1, help_text='How many posts to publish per month.'),
        ),
    ]
