# Generated by Django 5.2.1 on 2025-05-26 13:23

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0024_blogposttitlesuggestion_archived_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='project',
            name='html_content',
        ),
        migrations.RemoveField(
            model_name='projectpage',
            name='html_content',
        ),
    ]
