# Generated by Django 5.2.1 on 2025-05-12 06:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0025_remove_autosubmittionsettings_posts_per_day_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='blogposttitlesuggestion',
            name='posted',
        ),
        migrations.AddField(
            model_name='generatedblogpost',
            name='posted',
            field=models.BooleanField(default=False),
        ),
    ]
