# Generated by Django 5.2.1 on 2025-05-26 13:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0025_remove_project_html_content_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='project',
            name='location',
            field=models.CharField(default='Global', max_length=50),
        ),
    ]
