# Generated by Django 5.2.2 on 2025-07-06 13:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0027_autosubmissionsetting_delete_autosubmittionsetting'),
    ]

    operations = [
        migrations.AddField(
            model_name='project',
            name='enable_automatic_post_generation',
            field=models.BooleanField(default=True),
        ),
        migrations.AddField(
            model_name='project',
            name='enable_automatic_post_submission',
            field=models.BooleanField(default=False),
        ),
    ]
