# Generated by Django 5.2.5 on 2025-08-09 10:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0027_autosubmissionsetting_delete_autosubmittionsetting'),
    ]

    operations = [
        migrations.AddField(
            model_name='generatedblogpost',
            name='date_posted',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='profile',
            name='experimental_features',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='project',
            name='enable_automatic_post_generation',
            field=models.BooleanField(default=True),
        ),
        migrations.AddField(
            model_name='project',
            name='enable_automatic_post_submission',
            field=models.BooleanField(default=False),
        ),
    ]
