# Generated by Django 5.2.2 on 2025-07-06 13:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0028_project_enable_automatic_post_generation_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='generatedblogpost',
            name='date_posted',
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
