# Generated by Django 5.2.5 on 2025-08-13 07:19

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0028_generatedblogpost_date_posted_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='pricingpageupdatessuggestion',
            name='project',
        ),
        migrations.RemoveField(
            model_name='pricingpageupdatessuggestion',
            name='project_page',
        ),
        migrations.DeleteModel(
            name='CompetitorComparisonBlogPost',
        ),
        migrations.DeleteModel(
            name='PricingPageUpdatesSuggestion',
        ),
    ]
