# Generated by Django 5.2.5 on 2025-08-19 13:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0029_remove_pricingpageupdatessuggestion_project_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='keyword',
            name='got_people_also_search_for_keywords',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='keyword',
            name='got_related_keywords',
            field=models.BooleanField(default=False),
        ),
    ]
